language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - "pip install nose"
  - "pip install coveralls"
  - "curl -s http://www.defunct.cc/maxmind-geoip-samples.tar.gz | tar -xzC tests/"
script:
  - nosetests --with-coverage --cover-package=pygeoip
after_success:
  - coveralls
